## YAML Template.
server:
    port: 8082
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        password: ''
        url: jdbc:mariadb://localhost:3306/dcbapp
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: Welcome To Spring Data Tutorial